#!/usr/bin/env bash

declare TRACKING_INFO

HOOK_PATH=$(dirname "$0")
HOOK_CFG_PATH="$HOOK_PATH/tracking-info-format.cfg"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
COMMIT_MSG=$(<$1)

[[ ! -f $HOOK_CFG_PATH || ! -s $HOOK_CFG_PATH ]] && exit 0
TRACKING_INFO_FORMAT=$(<$HOOK_CFG_PATH)

if [ -z $TRACKING_INFO_FORMAT ]; then
    exit 0
fi

# the format of branch name is from git emc clone
if [[ $BRANCH_NAME =~ \/($TRACKING_INFO_FORMAT)$ ]]; then
    TRACKING_INFO=${BASH_REMATCH[1]}
fi

if [[ ! $COMMIT_MSG =~ \[($TRACKING_INFO_FORMAT)\] ]]; then
    echo "Warning, there is no tracking info in commit message."
else
    if [[ $TRACKING_INFO ]]; then
        # check if tracking info is in commit message
        if [[ $COMMIT_MSG != *"[$TRACKING_INFO]"* ]]; then
            echo "Warning, default tracking info [$TRACKING_INFO] not found in commit message."
        fi
    fi
fi

