#!/usr/bin/env bash

declare TRACKING_INFO

# Do nothing if commit message was given
if [[ $2 ]]; then
	exit 0
fi

HOOK_PATH=$(dirname "$0")
HOOK_CFG_PATH="$HOOK_PATH/tracking-info-format.cfg"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

[[ ! -f $HOOK_CFG_PATH || ! -s $HOOK_CFG_PATH ]] && exit 0
TRACKING_INFO_FORMAT=$(<$HOOK_CFG_PATH)

if [ -z $TRACKING_INFO_FORMAT ]; then
    exit 0
fi

# the format of branch name is from git emc clone
if [[ $BRANCH_NAME =~ \/($TRACKING_INFO_FORMAT)$ ]]; then
    TRACKING_INFO=${BASH_REMATCH[1]}
fi

if [[ $TRACKING_INFO ]]; then
    # Insert TRACKING_INFO at the start of the commit message file
    sed -i "1s/^/[$TRACKING_INFO] /" "$1"
fi

